from CatchBrains.wrappers.clip_reward import ClipReward
from CatchBrains.wrappers.discrete_actions import DiscreteActions
from CatchBrains.wrappers.reacher_weighted_reward import ReacherRewardWrapper
from CatchBrains.wrappers.relative_position import RelativePosition
